# Generated by Django 5.2 on 2025-06-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funtime_disco_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ticket_details', models.TextField(verbose_name='This is your e-ticket for Funtime Disco. Please do not show this to any real bouncer. Enjoy!')),
            ],
        ),
    ]
