# Generated by Django 5.2 on 2025-06-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakecardnumber', models.IntegerField(unique=True)),
                ('fakesortcode', models.IntegerField(unique=True)),
                ('fakenameoncard', models.CharField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
