# Generated by Django 5.2 on 2025-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_paymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='fakenameoncard',
            field=models.CharField(max_length=255),
        ),
    ]
