# Generated by Django 5.2 on 2025-06-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_paymentinfo_fakenameoncard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='fakecardnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='fakesortcode',
            field=models.IntegerField(),
        ),
    ]
