# Generated by Django 5.2 on 2025-06-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_paymentinfo_fakecardnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='fakecardnumber',
            new_name='fake_card_number',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='fakenameoncard',
            new_name='fake_name_on_card',
        ),
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='fakesortcode',
            new_name='fake_sort_code',
        ),
    ]
