# Generated by Django 5.2 on 2025-06-12 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_purchase_history_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history_class',
            name='purchaser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
