# Generated by Django 5.2 on 2025-06-13 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_purchase_history_class_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history_class',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
