# Generated by Django 5.2 on 2025-06-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_profile_picture_profile_update_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
